<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DosenSeeder extends Seeder
{
    public function run(): void
    {
        $dosen = [
            [
                'id_dosen' => 1,
                'nama_dosen' => 'ALDE ALANDA S.Kom M.T',
                'nidn' => '0025088802',
                'nip' => '198808252015041002',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'alde@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 2,
                'nama_dosen' => 'ALDO ERIANDA M.T S.ST',
                'nidn' => '003078904',
                'nip' => '198907032019031015',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 2,
                'email' => 'aldo@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 3,
                'nama_dosen' => 'CIPTO PRABOWO S.T M.T',
                'nidn' => '0002037410',
                'nip' => '197403022008121001',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'cipto@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 4,
                'nama_dosen' => 'DEDDY PRAYAMA S.Kom M.ISD',
                'nidn' => '0015048105',
                'nip' => '198104152006041002',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'deddy@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 5,
                'nama_dosen' => 'DEFNI S.Si M.Kom',
                'nidn' => '0007128104',
                'nip' => '198112072008122001',
                'jenis_kelamin' => 'Perempuan',
                'id_jurusan' => 1,
                'id_prodi' => 2,
                'email' => 'defni@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 6,
                'nama_dosen' => 'DENI SATRIA S.Kom M.Kom',
                'nidn' => '0028097803',
                'nip' => '197809282008121002',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 2,
                'email' => 'dns1st@gmail.com',
                'status' => 'active',
            ],
            [
                'id_dosen' => 7,
                'nama_dosen' => 'DWINY MEIDELFI S.Kom M.Cs',
                'nidn' => '0009058601',
                'nip' => '19860509201321131',
                'jenis_kelamin' => 'Perempuan',
                'id_jurusan' => 1,
                'id_prodi' => 3,
                'email' => 'dwinymeidelfi@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 8,
                'nama_dosen' => 'ERVAN ASRI S.Kom M.Kom',
                'nidn' => '0001097802',
                'nip' => '197809012008121231',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 2,
                'email' => 'ervan@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 9,
                'nama_dosen' => 'FAZROL ROZI M.Sc.',
                'nidn' => '0021078601',
                'nip' => '19860721201012006',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'fazrol@pnp.ac.id',
                'status' => 'active',
            ],
            [
                'id_dosen' => 10,
                'nama_dosen' => 'FITRI NOVA M.T S.ST',
                'nidn' => '102905985',
                'nip' => '198505292014042001',
                'jenis_kelamin' => 'Perempuan',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'fitrinova85@gmail.com',
                'status' => 'active',
            ],
            [
                'id_dosen' => 11,
                'nama_dosen' => 'MERI AZMI, S.T, M.Cs',
                'nidn' => '1029051231',
                'nip' => '1985052921231123',
                'jenis_kelamin' => 'Perempuan',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'meriazmi@gmail.com',
                'status' => 'active',
            ],
            [
                'id_dosen' => 12,
                'nama_dosen' => 'RONAL HADI, S.T, M.Kom',
                'nidn' => '102905123112',
                'nip' => '19850529212123112',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'ronalhadi@gmail.com',
                'status' => 'active',
            ],
            [
                'id_dosen' => 13,
                "nama_dosen" => "HUMAIRA, S.T, M.T",
                'nidn' => '10123111231',
                'nip' => '198505292154334',
                'jenis_kelamin' => 'Laki-laki',
                'id_jurusan' => 1,
                'id_prodi' => 1,
                'email' => 'humaira@gmail.com',
                'status' => 'active',
            ],
        ];

        DB::table('dosen')->insert($dosen);
    }
}
