<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dosen;
use Illuminate\Support\Facades\DB;

class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                "nama_dosen" => "ALDE ALANDA, S.Kom, M.T",
                "nidn" => "0025088802",
                "nip" => "198808252015041002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "alde@pnp.ac.id",
            ],
            [
                "nama_dosen" => "ALDO ERIANDA, M.T, S.ST",
                "nidn" => "003078904",
                "nip" => "198907032019031015",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "aldo@pnp.ac.id",
            ],
            [
                "nama_dosen" => "CIPTO PRABOWO, S.T, M.T",
                "nidn" => "0002037410",
                "nip" => "197403022008121001",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "cipto@pnp.ac.id",
            ],
            [
                "nama_dosen" => "DEDDY PRAYAMA, S.Kom, M.ISD",
                "nidn" => "0015048105",
                "nip" => "198104152006041002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "deddy@pnp.ac.id",
            ],
            [
                "nama_dosen" => "DEFNI, S.Si, M.Kom",
                "nidn" => "0007128104",
                "nip" => "198112072008122001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "defni@pnp.ac.id",
            ],
            [
                "nama_dosen" => "DENI SATRIA, S.Kom, M.Kom",
                "nidn" => "0028097803",
                "nip" => "197809282008121002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "dns1st@gmail.com",
            ],
            [
                "nama_dosen" => "DWINY MEIDELFI, S.Kom, M.Cs",
                "nidn" => "0009058601",
                "nip" => "198605092014042001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "dwinymeidelfi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "ERVAN ASRI, S.Kom, M.Kom",
                "nidn" => "0001097802",
                "nip" => "197809012008121001",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "ervan@pnp.ac.id",
            ],
            [
                "nama_dosen" => "FAZROL ROZI, M.Sc.",
                "nidn" => "0021078601",
                "nip" => "19860721201012006",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "fazrol@pnp.ac.id",
            ],
            [
                "nama_dosen" => "FITRI NOVA, M.T, S.ST",
                "nidn" => "1029058502",
                "nip" => "198505292014042001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "fitrinova85@gmail.com",
            ],
            [
                "nama_dosen" => "Ir. HANRIYAWAN ADNAN MOODUTO, M.Kom.",
                "nidn" => "0010056606",
                "nip" => "196605101994031003",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "mooduto@pnp.ac.id",
            ],
            [
                "nama_dosen" => "HENDRICK, S.T, M.T.,Ph.D",
                "nidn" => "0002127705",
                "nip" => "197712022006041000",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "EE",
                "jurusan" => "Teknik Elektro",
                "kode_prodi" => "4EC",
                "prodi" => "D4 - Teknik Elektronika",
                "email" => "hendrickpnp77@gmail.com",
            ],
            [
                "nama_dosen" => "HIDRA AMNUR, S.E., S.Kom, M.Kom",
                "nidn" => "0015048209",
                "nip" => "198204152012121002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "hidra@pnp.ac.id",
            ],
            [
                "nama_dosen" => "HUMAIRA, S.T, M.T",
                "nidn" => "0019038103",
                "nip" => "198103192006042002",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "humaira@pnp.ac.id",
            ],
            [
                "nama_dosen" => "IKHSAN YUSDA PRIMA PUTRA, S.H., LL.M",
                "nidn" => "0001107505",
                "nip" => "197510012006041002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "",
            ],
            [
                "nama_dosen" => "INDRI RAHMAYUNI, S.T, M.T",
                "nidn" => "0025068301",
                "nip" => "198306252008012004",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "indri@pnp.ac.id",
            ],
            [
                "nama_dosen" => "MERI AZMI, S.T, M.Cs",
                "nidn" => "0029068102",
                "nip" => "198106292006042001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "meriazmi@gmail.com",
            ],
            [
                "nama_dosen" => "Ir. Rahmat Hidayat, S.T, M.Sc.IT",
                "nidn" => "1015047801",
                "nip" => "197804152000121002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "rahmat@pnp.ac.id",
            ],
            [
                "nama_dosen" => "RASYIDAH, S.Si, M.M.",
                "nidn" => "0001067407",
                "nip" => "197406012006042001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "rasyidah@pnp.ac.id",
            ],
            [
                "nama_dosen" => "RIKA IDMAYANTI, S.T, M.Kom",
                "nidn" => "0022017806",
                "nip" => "197801222009122002",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "rikaidmayanti@pnp.ac.id",
            ],
            [
                "nama_dosen" => "RITA AFYENNI, S.Kom, M.Kom",
                "nidn" => "0018077099",
                "nip" => "197007182008012010",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "ritaafyenni@pnp.ac.id",
            ],
            [
                "nama_dosen" => "RONAL HADI, S.T, M.Kom",
                "nidn" => "0029017603",
                "nip" => "197601292002121001",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "ronalhadi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "TAUFIK GUSMAN,  S.S.T, M.Ds",
                "nidn" => "0010088805",
                "nip" => " 19880810 201903 1 012",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "taufikgusman@gmail.com",
            ],
            [
                "nama_dosen" => "YANCE SONATHA, S.Kom, M.T",
                "nidn" => "0029128003",
                "nip" => "198012292006042001",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "sonatha.yance@gmail.com",
            ],
            [
                "nama_dosen" => "Dr. Ir. YUHEFIZAR, S.Kom., M.Kom",
                "nidn" => "0013017604",
                "nip" => "197601132006041002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "yuhefizar@pnp.ac.id",
            ],
            [
                "nama_dosen" => "YULHERNIWATI, S.Kom, M.T",
                "nidn" => "0019077609",
                "nip" => "197607192008012017",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "yulherniwati@pnp.ac.id",
            ],
            [
                "nama_dosen" => "TRI LESTARI, S.Pd.,M.Eng.",
                "nidn" => "0005039205",
                "nip" => "199203052019032025",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "trilestari0503@gmail.com",
            ],
            [
                "nama_dosen" => "Fanni Sukma, S.ST., M.T",
                "nidn" => "0006069009",
                "nip" => "199006062019032026",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "fannisukma@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Andre Febrian Kasmar, S.T., M.T.",
                "nidn" => "0020028804",
                "nip" => "198802202019031009",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "andrefebrian@pnp.ac.id",
            ],
            [
                "nama_dosen" => "RONI PUTRA, S.Kom, M.T ",
                "nidn" => "0022078607",
                "nip" => "198607222009121004",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "rn.putra@gmail.com",
            ],
            [
                "nama_dosen" => "Ardi Syawaldipa, S.Kom.,M.T.",
                "nidn" => "0029058909",
                "nip" => "19890529 202012 1 003",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "ardi.syawaldipa@gmail.com",
            ],
            [
                "nama_dosen" => "Harfebi Fryonanda, S.Kom., M.Kom",
                "nidn" => "0310119101",
                "nip" => "19911110 202203 1 008",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "harfebi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Ideva Gaputra, S.Kom., M.Kom",
                "nidn" => "0012098808",
                "nip" => "198809122022031006",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "idevagaputra@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Yulia Jihan Sy, S.Kom., M.Kom",
                "nidn" => "1017078904",
                "nip" => "19890717 202203 2 010",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "yulia@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Andrew Kurniawan Vadreas, S.Kom., M.T	",
                "nidn" => "1021028702",
                "nip" => "19870221 202203 1 001",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "andrew@pnp.ac.id",
            ],
            [
                "nama_dosen" => "YORI ADI ATMA, S.Pd., M.Kom",
                "nidn" => "2010059001",
                "nip" => "19900510 202203 1 002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3MI",
                "prodi" => "Manajemen Informatika D-3",
                "email" => "yori@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Dr. Ulya Ilhami Arsyah, S.Kom., M.Kom",
                "nidn" => "0130039101",
                "nip" => "19910330 202203 1 004",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "ulya@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Hendra Rotama, S.Pd., M.Sn",
                "nidn" => "0218068801",
                "nip" => "19880618 202203 1 003",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "hendrarotama@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Sumema, S.Ds., M.Ds",
                "nidn" => "0008069103",
                "nip" => "19910608 202203 2 006",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "sumema@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Raemon Syaljumairi, S.Kom., M.Kom",
                "nidn" => "0017078407",
                "nip" => "19840717 201012 1 002",
                "jenis_kelamin" => "Laki-laki",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "raemon_syaljumairi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Mutia Rahmi Dewi, S.Kom., M.Kom",
                "nidn" => "0004099601",
                "nip" => "19960904 202203 2 018",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "4TRPL",
                "prodi" => "Teknologi Rekayasa Perangkat Lunak",
                "email" => "mutiarahmi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Novi, S.Kom., M.T",
                "nidn" => "0001118611",
                "nip" => "19861101 202203 2 003",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "novi@pnp.ac.id",
            ],
            [
                "nama_dosen" => "Rahmi Putri Kurnia, S.Kom., M.Kom",
                "nidn" => "0027089303",
                "nip" => "19930827 202203 2 012",
                "jenis_kelamin" => "Perempuan",
                "kode_jurusan" => "TI",
                "jurusan" => "Teknologi Informasi",
                "kode_prodi" => "3TK",
                "prodi" => "Teknik Komputer D-3",
                "email" => "rahmiputri@pnp.ac.id",
            ],
        ];
        foreach ($data as $key => $value) {
            $id_jurusan = DB::table('jurusan')->where('kode_jurusan', $value['kode_jurusan'])->select('id_jurusan')->first()->id_jurusan;
            $id_prodi = DB::table('prodi')->where('kode_prodi', $value['kode_prodi'])->select('id_prodi')->first()->id_prodi;
            $dosen = new Dosen;
            $dosen->id_dosen = array_search($value, $data) + 1;
            $dosen->nama_dosen = $value['nama_dosen'];
            $dosen->nidn = $value['nidn'];
            $dosen->nip = $value['nip'];
            $dosen->jenis_kelamin = $value['jenis_kelamin'];
            $dosen->id_jurusan = $id_jurusan;
            $dosen->id_prodi = $id_prodi;
            $dosen->email = $value['email'];
            $dosen->save();
        }
    }
}
